/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 */
import type { ParserConditions } from './parserConditions';

export interface Parser {
  readonly conditions?: ParserConditions;
  text: string;
}
