/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 */
import type { ParserConditionsPeriodsItem } from './parserConditionsPeriodsItem';

export type ParserConditions = {
  readonly amount_max?: string;
  readonly amount_min?: string;
  readonly periods: ParserConditionsPeriodsItem[];
};
