/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 */

export interface User {
  first_name?: string;
  readonly id?: number;
  readonly is_authenticated?: boolean;
  last_name?: string;
}
